project:
  type: website
  output-dir: docs

website:
  title: "DANE 2024"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: location.qmd
        text: Location
      - href: programme.qmd
        text: Programme
  page-footer:
    center:
      - text: "© 2024 King's College London. Contact: <a href=\"mailto:V.Koutra@kcl.ac.uk\">V.Koutra@kcl.ac.uk</a>"
      
execute: 
  echo: false

format:
  html:
    theme: journal
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>



