---
title: "Design and Analysis of Networked Experiments 2024"
subtitle: "17-19 July, King's College London"
---

## Programme

All scientific sessions are in Room K2.40. Coffee, lunch, tea and the reception are in the River Room.

```{r}
#| message: false
#| warning: false
library(gt)
library(readr)
library(janitor)
library(dplyr)

prog <- read_csv("data/programme.csv", 
                 col_types = cols(.default = col_character()))
prog <- clean_names(prog)
```


::: {.panel-tabset}

## Wednesday

```{r}
#| column: screen
prog |> 
  filter(day == "Wednesday") |>
  select(-day) |>
  gt(rowname_col = "time", groupname_col = "session") |>
  sub_missing(
    missing_text = ""
    ) |>
  fmt_markdown(
    columns = abstract
  ) |>
  tab_options(
    table.width = pct(100),
    column_labels.hidden = TRUE
    ) |>
  cols_width(
    time ~ pct(6),
    abstract ~ pct(50),
    speaker ~ pct(10),
    affiliation ~ pct(9),
    title ~ pct(15)
  ) |>
  cols_hide(columns = session) |>
  tab_style(
  style = list(
    cell_fill(color = "lightgrey")
  ),
  locations = cells_row_groups()
) |>
  text_transform(
    locations = cells_row_groups(),
    fn = function(x) {
      lapply(x, function(x) {
        x <- strsplit(x, split = " (", fixed = T)[[1]]
        if(length(x) > 1) {
          gt::md(paste0("**", x[[1]], "**", " (", x[[2]]))
        } else {
          gt::md(paste0("**", x[[1]], "**"))
        }
      })
    }
  )
```

## Thursday

```{r}
#| column: screen
prog |> 
  filter(day == "Thursday") |>
  select(-day) |>
  gt(rowname_col = "time", groupname_col = "session") |>
  sub_missing(
    missing_text = ""
    ) |>
  fmt_markdown(
    columns = abstract
  ) |>
  tab_options(
    table.width = pct(100),
    column_labels.hidden = TRUE
    ) |>
  cols_width(
    time ~ pct(6),
    abstract ~ pct(50),
    speaker ~ pct(10),
    affiliation ~ pct(9),
    title ~ pct(15)
  ) |>
  cols_hide(columns = session) |>
  tab_style(
  style = list(
    cell_fill(color = "lightgrey")
  ),
  locations = cells_row_groups()
) |>
  text_transform(
    locations = cells_row_groups(),
    fn = function(x) {
      lapply(x, function(x) {
        x <- strsplit(x, split = " (", fixed = T)[[1]]
        if(length(x) > 1) {
          gt::md(paste0("**", x[[1]], "**", " (", x[[2]]))
        } else {
          gt::md(paste0("**", x[[1]], "**"))
        }
      })
    }
  )
```

## Friday

```{r}
#| column: screen
prog |> 
  filter(day == "Friday") |>
  select(-day) |>
  gt(rowname_col = "time", groupname_col = "session") |>
  sub_missing(
    missing_text = ""
    ) |>
  fmt_markdown(
    columns = abstract
  ) |>
  tab_options(
    table.width = pct(100),
    column_labels.hidden = TRUE
    ) |>
  cols_width(
    time ~ pct(6),
    abstract ~ pct(50),
    speaker ~ pct(10),
    affiliation ~ pct(9),
    title ~ pct(15)
  ) |>
  cols_hide(columns = session) |>
  tab_style(
  style = list(
    cell_fill(color = "lightgrey")
  ),
  locations = cells_row_groups()
) |>
  text_transform(
    locations = cells_row_groups(),
    fn = function(x) {
      lapply(x, function(x) {
        x <- strsplit(x, split = " (", fixed = T)[[1]]
        if(length(x) > 1) {
          gt::md(paste0("**", x[[1]], "**", " (", x[[2]]))
        } else {
          gt::md(paste0("**", x[[1]], "**"))
        }
      })
    }
  )
```

:::



